### ISSUE TITLE
AdminTools won't load

### ISSUE THREAD

**Issue by Oyplap** [Exiled-Team/AdminTools#16]
I'm not sure what i am doing wrong.

I use Exiled Alpha 70 and the latest open beta build: 11.0.0-parabellum-beta-9-e4b1e8f3

![Schermafbeelding 2021-08-28 010929](https://user-images.githubusercontent.com/45702131/131197044-936d835a-4a34-4bad-b555-e7ecd98c2fb7.png)

**Comment by joker-119** [comment]
update the plugin

**Comment by Oyplap** [comment]
I have updated to the latest pre-release (3.0.1). My second server works but my first server does not.

**Comment by Oyplap** [comment]
Fixed it by using brain
