### ISSUE TITLE
Massive dummy error

### ISSUE THREAD

**Issue by growled** [Exiled-Team/AdminTools#17]
**Describe the bug**
So I spawned in 4 peanut dummies and then used dummy clearall to clear them all, we were messing around on the server with around 30 people on at the time. I try to do the same thing with a classd, trying to spawn a classd using dummy 24 1 10 5 0.001 or something and the server stayed active but booted everyone out onto that disconnect mode. Everyone stood still, but everyone stayed connected. You could still hear decontamination announcements etc but everyone had disconnected, it was really weird.

Main error that was spammed in LA logs was this:
[2021-08-31 12:07:57.111 +01:00] [STDOUT] (Filename: <722a70a0e41640b49345532843d65819> Line: 0)
[2021-08-31 12:07:57.111 +01:00] [STDOUT] NullReferenceException: Object reference not set to an instance of an object
[2021-08-31 12:07:57.112 +01:00] [STDOUT]   at PlayableScps.Scp173.OnUpdate () [0x000a1] in <722a70a0e41640b49345532843d65819>:0
[2021-08-31 12:07:57.113 +01:00] [STDOUT]   at PlayableScps.PlayableScp.BaseUpdate () [0x00000] in <722a70a0e41640b49345532843d65819>:0
[2021-08-31 12:07:57.113 +01:00] [STDOUT]   at PlayableScpsController.Update () [0x00056] in <722a70a0e41640b49345532843d65819>:0
[2021-08-31 12:07:57.114 +01:00] [STDOUT] (Filename: <722a70a0e41640b49345532843d65819> Line: 0)

**To Reproduce**
1. Not sure whether it's reproducible. I spawned in 4 peanut dummies using dummy <id> 0 10 3 0.001
2. dummy clearall
3. dummy <id> 1 10 5 0.001
4. It froze the server for me and everyone stood in place. On the console it said everyone had disconnected.

**Expected behavior**
The dummy would spawn normally.

**Server logs**
The server log is massive and exceeds the pastebin limit. DM me on discord (psycho boy#1337) and I'll send it over 

**EXILED Version ("latest" is not a version):** 3.0.0-alpha-76

**Results of `show plugins` command in console:**
[2021-08-31 12:20:18.865 +01:00] Total number of plugins: 17
Enabled plugins: 17
Disabled plugins: 0

Buddy:
        - Author: DGvagabond
        - Version: 1.4.0
        - Required Exiled Version: 3.0.0
        - Prefix: buddy
        - Priority: Highest
Exiled.Events:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_events
        - Priority: Highest
ReportPing:
        - Author: Jepp Developments
        - Version: 1.1.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: report_ping
        - Priority: High
PlayerList:
        - Author: SrLicht
        - Version: 1.0.6
        - Required Exiled Version: 3.0.0.0
        - Prefix: player_list
        - Priority: Medium
DiscordIntegration:
        - Author: Exiled Team
        - Version: 4.0.3.0
        - Required Exiled Version: 3.0.0
        - Prefix: discord_integration
        - Priority: Medium
Exiled.Updater:
        - Author: Exiled.Updater
        - Version: 3.1.1.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_updater
        - Priority: Medium
RespawnTimer:
        - Author: Michal78900
        - Version: 3.0.0
        - Required Exiled Version: 3.0.0
        - Prefix: respawn_timer
        - Priority: Medium
Exiled.CreditTags:
        - Author: Babyboucher20 & iRebbok & Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_credits
        - Priority: Medium
WaitAndChillReborn:
        - Author: Michal78900
        - Version: 3.0.1
        - Required Exiled Version: 3.0.0
        - Prefix: wait_and_chill_reborn
        - Priority: Medium
Admin Tools:
        - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
        - Version: 3.0.3
        - Required Exiled Version: 3.0.0
        - Prefix: AT
        - Priority: Medium
Ultimate AFK:
        - Author: Thomasjosif
        - Version: 3.1.6
        - Required Exiled Version: 3.0.0.0
        - Prefix: uAFK
        - Priority: Medium
Exiled.Permissions:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_permissions
        - Priority: Medium
Common Utilities:
        - Author: Galaxy119
        - Version: 4.0.2
        - Required Exiled Version: 3.0.0
        - Prefix: CommonUtilities
        - Priority: Medium
Ban Logger:
        - Author: Jesus-QC
        - Version: 1.0.7
        - Required Exiled Version: 3.0.0
        - Prefix: BanLogger
        - Priority: Medium
Exiled.CustomItems:
        - Author: Exiled Team
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: exiled_custom_items
        - Priority: Medium
Stalky106:
        - Author: RogerFK
        - Version: 3.0.0.0
        - Required Exiled Version: 3.0.0.0
        - Prefix: ST106
        - Priority: Medium
SCPStats:
        - Author: PintTheDragon
        - Version: 1.4.1
        - Required Exiled Version: 3.0.0
        - Prefix: scp_stats
        - Priority: Lowest

**Additional context**
N/A

**Comment by joker-119** [comment]
I will test to see if i can reproduce, but this sounds a lot like https://trello.com/c/hwVJf8B6/2962-i-cant-interact-with-any-doors-after-an-amount-of-time and the exception you gave is purely base-game, not something EXILED even interacts with.
