### ISSUE TITLE
all command permissions can be limited

### ISSUE THREAD

**Issue by JustJesseGITHUB** [Exiled-Team/AdminTools#23]
at.size: max_scale:1.1 so they can only go up to 1.1 in size

**Comment by JustJesseGITHUB** [comment]
example in description

**Comment by joker-119** [comment]
Arbitrarily limiting commands to certain values is contradictory to the purpose of admin tools, and making config options for every single command is extremely time consuming for little gain since almost no one will need them, they will just clutter up peoples config files.
