### ISSUE TITLE
KICKED FROM SERVER WHEN SHOOTING DUMMY (and anything else after)

### ISSUE THREAD

**Issue by Purriku** [Exiled-Team/AdminTools#24]
Kicked from server when shooting dummy. After that you will be kicked when shooting anything with a hit box (target, player, ect.) until console is restarted. **JUST TESTED 9/14/21 9pm est ONCE DUMMY SPAWNED YOU WILL BE KICKED FOR FIRING YOUR WEAPON REGARDLESS OF HIT**

**To Reproduce**
1. spawn dummy
2. shoot it
3. get kicked
4. reconnect
5. shoot your friend now or even your teamate with ff on or off
6. get kicked again. 
7. no matter who you shoot now. you will get kicked. 
8. Restart of console is only temporary fix until someone spawns and shoots a dummy again.

**Server logs**
https://pastebin.com/Sb063eTv

**EXILED Version (alpha 84):**

**Results of `show plugins` command in console:*
https://pastebin.com/2d6Ctw44

**Comment by Purriku** [comment]
JUST TESTED 9/14/21 9pm est ONCE DUMMY SPAWNED YOU WILL BE KICKED FOR FIRING YOUR WEAPON REGARDLESS OF HIT

**Comment by joker-119** [comment]
This is a base-game issue (and has already been reported, please look at closed issues before posting bug reports)
