### ISSUE TITLE
Crashing when shooting dummy

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/AdminTools#29]
**Describe the bug**
Please include a pastebin of your localadmin log file (or both MA_log and SCP_log files if you use MultiAdmin) from the time in which the bug occured

**To Reproduce**
1. Go to Text-based admin panel
2. Enter "Dummy (playerid) (any role) 1 1 1"
3. Give yourself a gun
4. Shoot the dummy anywhere

**Expected behavior**
Nothing.

**Server logs**
https://pastebin.com/G86DiUXm

**EXILED Version ("latest" is not a version):**
Unsure what the current EXILED version is when making this

**Results of `show plugins` command in console:**
Total Number of plugins: 18
Enabled plugins: 17
DIsabled Plugins: 1

**Comment by joker-119** [comment]
This is the result of base-game choices on networking, and I have no intention to fix it. Use dummies at your own risk.
