### ISSUE TITLE
/kick ignoring kick_power and required_kick_power

### ISSUE THREAD

**Issue by SoraCent** [Exiled-Team/AdminTools#34]
**Describe the bug**
Idk if it's a bug or not possible to implement but Users with less Kickpower can kick users which uses higher kick powers for beeing kicked.

**To Reproduce**
1. Create 2 Users in Remoteadmin
2. One has less Kick Power than the other and the Required_Kick_Power needs to be higher too
3. Open RA and use the /kick command on a User with the higher role
4. User getting Kicked which shouldn't be the case

**Expected behavior**
There should be an info that the user can't be kicked

**Server logs**
No logs

**EXILED Version ("latest" is not a version):**
EXILED-4.1.6
AT: 4.0.0

**Results of `show plugins` command in console:**
Don't needed because no other Plugin handling the kicks

**Comment by joker-119** [comment]
The AT kick command doesn't implement the kick_power stuff because NW made it (at least originally) really dumb to get a user's kick power etc. I'll look into it again.

**Comment by yooooxghashg** [comment]
joker, where da update at?, some bugs needa be fixed
