### ISSUE TITLE
spawnragdoll is not spawning any ragdolls

### ISSUE THREAD

**Issue by Firexik** [Exiled-Team/AdminTools#35]
**Describe the bug**
spawnragdoll is not spawning any ragdolls even tho the console responce is that a ragdoll has been spawned.

**To Reproduce**
1. type spawnragdoll (playerid) (roleid) (amount)
2. press enter
3. see that nothing happended ;(

**Expected behavior**
a ragdoll is supposed to drop from the sky

**Server logs: https://pastebin.com/PbFbQ6RP**

**EXILED Version: 4.1.7**

**Results of `show plugins` command in console: https://imgur.com/a/3xYsvdP**

**Additional context**
please fix the ammo issue with common utilities, im waiting for the fix for at least a month... thanks and lots of love during holidays.

**Comment by KrisPrs** [comment]
*Still happends on Exiled 5.0

**Comment by joker-119** [comment]
I'll need your localadmin logs

**Comment by Thundermaker300** [comment]
[LocalAdmin_Log_2022-06-08_19.30.53.txt](https://github.com/Exiled-Team/AdminTools/files/8866408/LocalAdmin_Log_2022-06-08_19.30.53.txt)

**Comment by Thundermaker300** [comment]
@joker-119 Any updates?

**Comment by joker-119** [comment]
This was fixed in the last update
