### ISSUE TITLE
Spawn Workbench not working

### ISSUE THREAD

**Issue by Draconic99** [Exiled-Team/AdminTools#38]
**Describe the bug**
using the spawn workbench command doesn't do anything but if someone else stands where you created one they start floating

**To Reproduce**
1. Go to ra panel
2. Click on text based ra
3. use spawn workbench command
4. workbench is invisible, get someone else to stand where it is and they will start floating as well

**Expected behavior**

**Server logs**
Please include a pastebin of your localadmin log file (or both MA_log and SCP_log files if you use MultiAdmin) from the time in which the bug occured

**EXILED Version ("latest" is not a version):**

**Results of `show plugins` command in console:**

**Additional context**

**Comment by joker-119** [comment]
Please actually include the information requested in the template, such as the server logs, exiled version and show plugins output.
