### ISSUE TITLE
[MAJOR BUG] Unjail command bugs players

### ISSUE THREAD

**Issue by xRoier** [Exiled-Team/AdminTools#47]
**Describe the bug**
When you unjail someone that player is now invincible, frozen and duplicated, also when someone tries to hurt them they get kicked from the server.

**To Reproduce**
1. Put someone in jail.
2. Unjail him.
3. Hurt him.
4. Get kicked.
Video: https://youtu.be/6Ykq998VUDY

**Expected behavior**
Not get kicked, frozen, invincible or/and duplicated.

**Server logs**
SCP: https://pastebin.com/mrTGNK1C
MA: https://pastebin.com/nua5Bwt5

**EXILED Version ("latest" is not a version):**
5.1.3

**Results of `show plugins` command in console:**
Admin Tools:
        - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
        - Version: 5.0.0.0
        - Required Exiled Version: 5.0.0
        - Prefix: AT
        - Priority: Medium

**Comment by GabiRP** [comment]
The actual steps to reproduce are:

1. Jail someone
2. Make them disconnect and reconnect
3. Unjail them
4. Try to hurt them

**Comment by joker-119** [comment]
Ok, I'll try that. That's confirmed to cause the bug on the newest version I just released today?
And that bug doesn't occur if they don't disconnect before being unjailed?

**Comment by joker-119** [comment]
Ok, that helps narrow down the issue a lot, thank you.
