### ISSUE TITLE
Grenade command doesn't work with Scp2176

### ISSUE THREAD

**Issue by Thundermaker300** [Exiled-Team/AdminTools#51]
**Describe the bug**
The "grenade" command does not work with Scp2176 inputted, even though Scp2176 is a GrenadeType according to Exiled.

**To Reproduce**
1. Run "grenade [playerId] Scp2176 [fuseTime]
2. error

**Expected behavior**
Should spawn a ghost bulb with the given time left until it explodes.

[Image](https://cdn.discordapp.com/attachments/977048248579670016/986024080719347813/unknown.png)

**Comment by Misfiy** [comment]
AdminTools has been reworked a lot, thus this issue will be closed. You may open a new issue if this is still causing issues on the new version.
