### ISSUE TITLE
WorkBench Spawning not working.

### ISSUE THREAD

**Issue by RealDemonBoi** [Exiled-Team/AdminTools#54]
If you try to spawn a workbench at specific coordinates it will just say: Done! Spawned in -1 workbenches.

**Comment by AtomSnow** [comment]
This issue exists since Parabellum, will try pushing PR

**Comment by Misfiy** [comment]
AdminTools has been reworked a lot, thus this issue will be closed. You may open a new issue if this is still causing issues on the new version.
