### ISSUE TITLE
Jail spawn broken

### ISSUE THREAD

**Issue by DemonMan4568** [Exiled-Team/AdminTools#55]
Jail command spawning in a weird spot above gate b roof.

**Comment by BenFRC5147** [comment]
In EventHandlers.cs line 189 reads

`player.Position = new Vector3(53f, 1020f, -44f);`

it should read `player.Position = new Vector3(40f, 1015f, -33f);`

This is the new position of tower (also default location of Tutorial spawn now, it seems.)

**Comment by louis1706** [comment]
Yeap it's do not need to set Player Position now
