### ISSUE TITLE
Jail don't keep in memory the effect of the player like Scp207 and candy

### ISSUE THREAD

**Issue by louis1706** [Exiled-Team/AdminTools#65]
**Describe the bug**
It's remove jail and unjail the players remove all of this effect

**To Reproduce**
1. Drink nice Scp207 (coca cola)
2. Send jail 
3. Send unjail
4. See effect disappeared 

**Expected behavior**
Keep all the effect in memory to give it back when unjailed

**EXILED Version ("latest" is not a version):**
Exiled 6.0.0

**Comment by Misfiy** [comment]
AdminTools has been reworked a lot, thus this issue will be closed. You may open a new issue if this is still causing issues on the new version.
