### ISSUE TITLE
Respawn after changing size to .1 unable player to move

### ISSUE THREAD

**Issue by Num10ck** [Exiled-Team/AdminTools#70]
**Describe the bug**
Changing size to 0.1 and changing role unable player to move
https://youtu.be/2dpsK2Cv-mo

**To Reproduce**
1. Change size to 0.1
2. Force start
or
1. Change size to 0.1
2. Spawn as any role

**Expected behavior**
Player can move

**EXILED Version ("latest" is not a version):**
Exiled.Loader - Version 7.0.0-rc.3

**Results of `show plugins` command in console:**
Don't have permissions. Plugins folder contain:
AdminTools.dll (Update to SL 12)
Exiled.CreditTags.dll
Exiled.CustomItems.dll
Exiled.CustomRoles.dll
Exiled.Events.dll
Exiled.Permissions.dll
Exiled.Updater.dll

**Server logs**
No logs. 
size 17 .1 .1 .1 
forcestart
noclip 17 1
size reset

**EXILED Version ("latest" is not a version):**
Exiled.Loader - Version 7.0.0-rc.3

**Additional context**
You can fly by noclip. To be able to move again need to rejoin server or restart round. Size reset didn't do anything.

**Comment by Num10ck** [comment]
Screenshot with stucked player. Him unable to move and have animation that looks like falling 
![20230528214039_1](https://github.com/Exiled-Team/AdminTools/assets/71600441/3b61a848-4f49-444e-8afa-2bd751c1e6b3)

**Comment by joker-119** [comment]
Purpose of plugin: To give admins a list of funky command thingies they can use to do funny shit
Not the purpose of the plugin: To ensure that all possible funny things admins can do, do not have negative side effects because of the limitations of the game.
